### ISSUE TITLE
New riddle

### ISSUE THREAD

**Issue by Anssett** [Khrysis-aard/plugins#3]
In case you're still looking and updating :)

What is the magic bean related to?
the Mexican Jumping Bean

relevant data:

A magic bean bounces happily here.  You think it must be related to the
Mexican Jumping Bean, the way it goes up and down, up and down, up and down,
up and down...  It's almost hypnotic, the way it's moving, and you feel
yourself getting very sleepy...  
A magic bean is bleeding lightly.

**Comment by Khrysis-aard** [comment]
Thank you. That was the first plug-in I made so it definitely still needs some updating. Haven't worked on it lately but I'll probably get around to adding that and fixing some of the other stuff. Thanks again.
